const Productdetail = [
  {
    id: 1,
    Title: "Lenovo Tab P12 Pro tablet",
    Cat: "Tablet",
    Price: "723",
    Img: "./img/Lenovo Tab P12 Pro tablet.png",
  },
  {
    id: 2,
    Title: "CPU Cooler 2 Heat Pipes 12mm 4 Pin PWM RGB for Intel",
    Cat: "Heat pipe",
    Price: "156",
    Img: "./img/CPU Cooler 2 Heat Pipes 12mm 4 Pin PWM RGB for Intel.png",
  },
  {
    id: 3,
    Title: "Playstation 4 2TB Slim Gaming Console",
    Cat: "Gaming",
    Price: "2098",
    Img: "./img/Playstation 4 2TB Slim Gaming Console.png",
  },
  {
    id: 4,
    Title: "Mini Portable Mobile Phone Powerbank for iphone",
    Cat: "Powerbank",
    Price: "386",
    Img: "./img/Mini Portable Mobile Phone Powerbank for iphone2.png",
  },
  {
    id: 5,
    Title: "Tracker with IP67 Waterproof Pedometer Smart watch",
    Cat: "Smart Watch",
    Price: "168",
    Img: "./img/Tracker with IP67 Waterproof Pedometer Smart watch.png",
  },
  {
    id: 6,
    Title: "Cancelling Headphones Wireless",
    Cat: "Headphone",
    Price: "49",
    Img: "./img/Cancelling Headphones Wireless.png",
  },
  {
    id: 7,
    Title: "Professional Camera 4K Digital Video Camera",
    Cat: "Camera",
    Price: "1049",
    Img: "./img/Professional Camera 4K Digital Video Camera.png",
  },
  {
    id: 8,
    Title: "Mini Portable Mobile Phone Powerbank for iphone",
    Cat: "Powerbank",
    Price: "49",
    Img: "./img/Mini Portable Mobile Phone Powerbank for iphone.png",
  },
  {
    id: 9,
    Title: "Microsoft Surface Pro 8-13' Touchscreen",
    Cat: "Tablet",
    Price: "693",
    Img: "./img/Microsoft Surface Pro 8-13' Touchscreen.png",
  },
  {
    id: 10,
    Title: "Playstation 5 2TB Slim Gaming Console",
    Cat: "Gaming",
    Price: "5098",
    Img: "./img/Playstation 5 2TB Slim Gaming Console.png",
  },
  {
    id: 11,
    Title: "Echo Show 5 (2nd Gen) Adjustable Stand | Charcoal",
    Cat: "Electronics",
    Price: "198",
    Img: "./img/Echo Show 5 (2nd Gen) Adjustable Stand  Charcoal.png",
  },
  {
    id: 12,
    Title: "Echo Dot smart speaker",
    Cat: "Electronics",
    Price: "793",
    Img: "./img/Echo Dot smart speaker.png",
  },
];
export default Productdetail;
